### ISSUE TITLE
CI: Add GHA to publish rendered example on gh-pages?

### ISSUE THREAD

**Issue by mcanouil** [quarto-ext/fontawesome#11]
I noticed the rendered examples are published on `gh-pages` but there isn't any CI allowing the files to be properly updated on code changes in `main`.
Should we (I) add something like:

```yaml
on:
  push:
    branches: main

name: Quarto render examples

jobs:
  render-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_EMAIL: ${{ github.actor }}@users.noreply.github.com
          target: gh-pages
          path: example.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
