### ISSUE TITLE
Incorrect path to fonts generated with Quarto v1.2+

### ISSUE THREAD

**Issue by andrewheiss** [quarto-ext/fontawesome#16]
I'm not sure if this is an issue with this extension specifically or an issue with Quarto v1.2's handling of external HTML resources.

When using Quarto v1.1.251, the path to the font files that is generated in `all.css` (`site_libs/quarto-contrib/fontawesome6-0.1.0/all.css`) correctly references the files that are placed in the `webfonts` directory one level back:

```css
@font-face {
  font-family: 'Font Awesome 6 Free';
  ...
  src: url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.ttf") format("truetype"); }
```

When using Quarto v1.2.134 (and earlier iterations of v1.2), the path does not include `../webfonts/`, which makes the fonts fail to load in the browser:

```css
@font-face {
  font-family: 'Font Awesome 6 Free';
  ...
  src: url("fa-regular-400.woff2") format("woff2"), url("fa-regular-400.ttf") format("truetype"); }
```

![image](https://user-images.githubusercontent.com/73663/191313344-d2755578-2531-4457-b026-bb13b7006ccb.png)
